<?xml version='1.0' encoding='UTF-8'?>
<UPDATES Version="1.5.0.0" Source="git">
  <UPDATE>
    <DATE Year="2021" Month="6" Day="15"/>
    <TIME Timezone="UTC" Hour="16" Minute="5" Second="36"/>
    <OS Repo="ports" Id="FreeBSD" Branch="2021Q2"/>
    <LOG>security/py-fail2ban: Create required start dir

Reported at https://github.com/fail2ban/fail2ban/issues/2634
fail2ban should check and, if necessary create, the required directory.

It is still up to the user to ensure that configuration in fail2ban's
conf files and FreeBSD's /etc/rc.conf are in sync and that both, pidfile
and socket reside in the same directory.

PR:		244092
Approved by:	maintainer
MFH:		2021Q2

(cherry picked from commit b48d2a658ef96565393b9186cbed85803b2b87e0)</LOG>
    <PEOPLE>
      <COMMITTER CommitterName="Kevin Bowling" CommitterEmail="kbowling@FreeBSD.org"/>
      <AUTHOR AuthorName="Florian Koczan" AuthorEmail="theis@gmx.at"/>
    </PEOPLE>
    <COMMIT Hash="82ad1b7e038ab9a71929742ad86b4bf463d0709d" HashShort="82ad1b7e" Subject="security/py-fail2ban: Create required start dir" EncodingLoses="false" Repository="ports"/>
    <FILES>
      <FILE Action="Modify" Path="security/py-fail2ban/Makefile"/>
      <FILE Action="Modify" Path="security/py-fail2ban/files/fail2ban.in"/>
    </FILES>
  </UPDATE>
</UPDATES>
